# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20170321_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourseRegistraion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scr_registration_date', models.DateField(default=django.utils.timezone.now)),
                ('scr_is_completed', models.BooleanField(default=False)),
                ('scr_completion_date', models.DateField(default=django.utils.timezone.now)),
                ('scr_course_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.CourseInfo')),
                ('scr_user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.AppUser')),
            ],
        ),
    ]
