# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_studentcourseregistraion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentCourseRegistraion',
            new_name='StudentCourseRegistration',
        ),
    ]
