# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20170324_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourseregistration',
            name='scr_training_center_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.TrainingCenter'),
        ),
    ]
