# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20170324_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourseregistration',
            name='scr_course_id',
        ),
        migrations.RemoveField(
            model_name='studentcourseregistration',
            name='scr_training_center_id',
        ),
        migrations.RemoveField(
            model_name='studentcourseregistration',
            name='scr_user_id',
        ),
        migrations.DeleteModel(
            name='StudentCourseRegistration',
        ),
    ]
