# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_studentcourseregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFeedbackDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfd_subject', models.CharField(blank=True, max_length=255)),
                ('cfd_detail', models.TextField(blank=True)),
                ('cfd_feedback_date', models.DateField(default=django.utils.timezone.now)),
                ('cfd_rating', models.IntegerField(default=0)),
                ('cfd_course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CourseInfo')),
                ('cfd_training_center_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TrainingCenter')),
                ('cfd_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AppUser')),
            ],
        ),
        migrations.AlterField(
            model_name='studentcourseregistration',
            name='scr_course_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.CourseInfo'),
        ),
        migrations.AlterField(
            model_name='studentcourseregistration',
            name='scr_user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.AppUser'),
        ),
    ]
