# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20170324_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefeedbackdetail',
            name='cfd_rating',
            field=models.IntegerField(default=1),
        ),
    ]
