# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20170324_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateIndia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('si_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StatewiseDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sd_district_name', models.CharField(max_length=255)),
                ('sd_state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.StateIndia')),
            ],
        ),
    ]
